# Define a pasta a ser publicada e a localização das funções de servidor.
[build]
  publish = "/"
  functions = "netlify/functions"

# Regra para redirecionar pedidos de '/api/config' para a função de servidor correspondente.
# Isto cria um atalho amigável e seguro para a nossa função.
[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200

# Regra para redirecionar pedidos de '/api/gemini' para a função de servidor do Gemini.
[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200

