# Define a pasta a ser publicada e a localização das funções de servidor.
[build]
  publish = "/"
  functions = "netlify/functions"

# Regra para redirecionar pedidos de '/api/gemini' para a função de servidor do Gemini.
# Esta é a única regra necessária agora.
[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200

