# Este comando diz ao Netlify para executar o nosso script 'build.sh' antes de publicar o site.
[build]
  command = "bash build.sh"
  publish = "/"
  functions = "netlify/functions"

# Esta regra direciona os pedidos para a função segura do Gemini.
[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200

