[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200

